### ISSUE TITLE
Got error when starting

### ISSUE THREAD

**Issue by pierrecdlc** [J-M1/Raffle-Notifier#1]
`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './classes/Webhook'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/node_modules/discord-webhook-node/src/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`

May you help me ?
Thank you !

**Comment by J-M1** [comment]
Try `npm install discord-webhook-node`.

**Comment by pierrecdlc** [comment]
Still got the same error, I did nodejs raffle.js
And got same error

**Comment by J-M1** [comment]
I've just updated the code, retry it with the new version. Remember `node raffle.js` instead of `nodejs raffle.js`.

**Comment by pierrecdlc** [comment]
ok thx lemme check

**Comment by pierrecdlc** [comment]
Still got the error... Tried with a brand new droplet

**Comment by pierrecdlc** [comment]
<img width="1212" alt="Screen Shot 2020-03-26 at 1 38 40 PM" src="https://user-images.githubusercontent.com/24671155/77647663-1bfb7380-6f67-11ea-8f46-fe2ebf311915.png">

**Comment by J-M1** [comment]
I haven't ran it on a server so I'm not sure. This is only meant to be used as a reference, not to be used in production.

I have just tested it and it works fine on my local machine.

**Comment by J-M1** [comment]
Closing old issues.
